version: 2.1
jobs:
  build_test:
    working_directory: ~/
    docker:
      - image: circleci/node:14.15.1-browsers
    steps:
      - run:
          name: Change directory public
          command: mkdir public && cd public
      - run:
          name: Change directory build
          command: mkdir build && cd build
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "./package-lock.json" }}
      - run:
          name: Setup
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "./package-lock.json" }}
          paths:
            - ~/public/.node_modules
      - run:
          name: Build Lazyload Library
          command: npm run build:lazyload
      - run:
          name: Build main showcase app
          command: npm run build
      - persist_to_workspace:
          root: /public
          paths:
            - build/*
  test:
    working_directory: ~/
    docker:
      - image: circleci/node:14.15.1-browsers
    steps:
      - attach_workspace:
          at: /tmp/public
      - run:
          name: ls -a
          command: ls -a
      - run:
          name: Test main showcase app
          command: npm run test
  deploy:
    working_directory: ~/
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: /tmp/public
      - run:
          name: Check project name
          command: echo ${PROJECT_NAME}
      - run:
          name: Check project name2
          command: ${PROJECT_NAME}
      - run:
          name: Setup gcloud config
          command: ${GCLOUD_KEY} | base64 --decode | gcloud auth activate-service-account --key-file=- gcloud --quiet config set project ${GCLOUD_PROJECT} gcloud --quiet config set compute/zone ${GCLOUD_ZONE}
      - run:
          name: Run Deploy
          command: gcloud app deploy
workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop
