version: 2.1
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:14.15.1-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "./package-lock.json" }}
      - run:
          name: Setup
          command: npm ci
      - run:
          name: Build Lazyload Library
          command: npm run build:lazyload
      - run:
          name: Build main showcase app
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - node_modules
  test:
    working_directory: ~/test
    docker:
      - image: circleci/node:14.15.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: ls -a
          command: ls -a
      - run:
          name: Test main showcase app
          command: npm run test
  deploy:
    working_directory: ~/deploy
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Check project name
          command: echo ${PROJECT_NAME}
      - run:
          name: Check project name2
          command: ${PROJECT_NAME}
      - run:
          name: Setup gcloud config
          command: ${GCLOUD_KEY} | base64 --decode | gcloud auth activate-service-account --key-file=- gcloud --quiet config set project ${GCLOUD_PROJECT} gcloud --quiet config set compute/zone ${GCLOUD_ZONE}
      - run:
          name: Run Deploy
          command: gcloud app deploy
workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop
